// export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
export const IMAGES_PATH = process.env.NEXT_PUBLIC_IMAGES_PATH;
export const PRIVACY_DOCUMENT_PATH = process.env.NEXT_PUBLIC_PRIVACY_DOCUMENT_PATH;
export const ACCESSIBILITY_DOCUMENT_PATH = process.env.NEXT_PUBLIC_ACCESSIBILITY_DOCUMENT_PATH;

export const PAGOPA_HOME = process.env.NEXT_PUBLIC_PAGOPA_HOME;
export const PAGOPA_HELP_EMAIL = process.env.NEXT_PUBLIC_PAGOPA_HELP_EMAIL;

export const PN_URL = process.env.NEXT_PUBLIC_PIATTAFORMA_NOTIFICHE_URL;