AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  PATooManyErrorsAlarmArn:
    Type: String
    Description: ARN of distribution too many errors alarm

  PATooManyRequestsAlarmArn:
    Type: String
    Description: ARN of distribution too many requests alarm
  
  PFTooManyErrorsAlarmArn:
    Type: String
    Description: ARN of distribution too many errors alarm

  PFTooManyRequestsAlarmArn:
    Type: String
    Description: ARN of distribution too many requests alarm

  PFLoginTooManyErrorsAlarmArn:
    Type: String
    Description: ARN of distribution too many errors alarm

  PFLoginTooManyRequestsAlarmArn:
    Type: String
    Description: ARN of distribution too many requests alarm

  LandingTooManyErrorsAlarmArn:
    Type: String
    Description: ARN of distribution too many errors alarm

  LandingTooManyRequestsAlarmArn:
    Type: String
    Description: ARN of distribution too many requests alarm

  PGTooManyErrorsAlarmArn:
    Type: String
    Default: ''
    Description: ARN of portale-pg distribution too many errors alarm

  PGTooManyRequestsAlarmArn:
    Type: String
    Default: ''
    Description: ARN of portale-pg distribution too many requests alarm

  StatusTooManyErrorsAlarmArn:
    Type: String
    Default: ''
    Description: ARN of status distribution too many errors alarm

  StatusTooManyRequestsAlarmArn:
    Type: String
    Default: ''
    Description: ARN of status distribution too many requests alarm

Resources:
  # Dashboard
  FrontendMicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-frontend"
        AlarmArns: !Join
          - ','
          - - !Ref PATooManyErrorsAlarmArn 
            - !Ref PATooManyRequestsAlarmArn
            - !Ref PFTooManyErrorsAlarmArn
            - !Ref PFTooManyRequestsAlarmArn
            - !Ref PFLoginTooManyErrorsAlarmArn
            - !Ref PFLoginTooManyRequestsAlarmArn
            - !Ref LandingTooManyErrorsAlarmArn
            - !Ref LandingTooManyRequestsAlarmArn
            - !Ref PGTooManyErrorsAlarmArn
            - !Ref PGTooManyRequestsAlarmArn
            - !Ref StatusTooManyErrorsAlarmArn
            - !Ref StatusTooManyRequestsAlarmArn
