export enum PGEventsType {
  // CONTACT
  SEND_PG_YOUR_CONTACT_DETAILS = 'SEND_PG_YOUR_CONTACT_DETAILS',

  // MANDATE
  SEND_PG_ADD_MANDATE_START = 'SEND_PG_ADD_MANDATE_START',
  SEND_PG_ADD_MANDATE_UX_SUCCESS = 'SEND_PG_ADD_MANDATE_UX_SUCCESS',
  SEND_PG_MANDATES_RECEIVED = 'SEND_PG_MANDATES_RECEIVED',
  SEND_PG_MANDATES_GIVEN = 'SEND_PG_MANDATES_GIVEN',

  // NAVIGATION
  SEND_PG_OPEN_USERS = 'SEND_PG_OPEN_USERS',
  SEND_PG_OPEN_GROUPS = 'SEND_PG_OPEN_GROUPS',
  SEND_PG_HELP = 'SEND_PG_HELP',
  SEND_PG_EXIT = 'SEND_PG_EXIT',

  // NOTIFICATION
  SEND_PG_YOUR_NOTIFICATION = 'SEND_PG_YOUR_NOTIFICATION',
  SEND_PG_NOTIFICATION_DETAIL = 'SEND_PG_NOTIFICATION_DETAIL',
  SEND_PG_NOTIFICATION_DELEGATED = 'SEND_PG_NOTIFICATION_DELEGATED',
}
