import {
  DeliveryMode,
  DigitaErrorTypes,
  NotificationStatus,
  ResponseStatus,
  StatisticsResponse,
} from '../../models/Statistics';

export const statisticsMockResponse: StatisticsResponse = {
  sender_id: '1c93d069-82c3-4903-a1ae-670353d9ad4d',
  genTimestamp: '2024-04-24T11:09:36.432251Z',
  lastDate: '2024-04-21',
  startDate: '2023-12-06',
  endDate: '2024-04-24',
  notifications_overview: [
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 49,
      delivery_time: 35419.6,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 2.77,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 4,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.11,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 38,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 67.24,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 564,
      delivery_time: 257041.82,
      view_time: 0.0,
      refinement_time: 345965.16,
      validation_time: 31.62,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 133,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 83487.85,
      validation_time: 7.63,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 101,
      delivery_time: 27.05,
      view_time: 0.0,
      refinement_time: 16998.84,
      validation_time: 5.45,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 4,
      notifications_count: 1,
      delivery_time: 170.3,
      view_time: 0.0,
      refinement_time: 530.36,
      validation_time: 0.06,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 2,
      notifications_count: 1,
      delivery_time: 169.18,
      view_time: 0.0,
      refinement_time: 529.24,
      validation_time: 0.05,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 73,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 200.7,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 132,
      delivery_time: 28.9,
      view_time: 14949.64,
      refinement_time: 8904.52,
      validation_time: 7.23,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 42,
      delivery_time: 0.0,
      view_time: 6300.67,
      refinement_time: 6302.94,
      validation_time: 2.27,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 1,
      delivery_time: 0.0,
      view_time: 0.02,
      refinement_time: 0.09,
      validation_time: 0.07,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 4,
      notifications_count: 1,
      delivery_time: 170.25,
      view_time: 528.44,
      refinement_time: 528.47,
      validation_time: 0.03,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 1,
      notifications_count: 1,
      delivery_time: 1.11,
      view_time: 232.78,
      refinement_time: 169.14,
      validation_time: 0.04,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 54,
      delivery_time: 37194.88,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 8.47,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 41,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 1.95,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 574,
      delivery_time: 216403.54,
      view_time: 0.0,
      refinement_time: 311443.92,
      validation_time: 40.56,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 134,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 74775.4,
      validation_time: 7.1,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 79,
      delivery_time: 16.77,
      view_time: 0.0,
      refinement_time: 13292.18,
      validation_time: 4.13,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 2,
      notifications_count: 3,
      delivery_time: 504.39,
      view_time: 0.0,
      refinement_time: 1584.58,
      validation_time: 0.18,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 1,
      notifications_count: 1,
      delivery_time: 170.13,
      view_time: 0.0,
      refinement_time: 337.17,
      validation_time: 0.04,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.REFUSED,
      notification_status: NotificationStatus.REFUSED,
      notification_type: DeliveryMode.UNKNOWN,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 1,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.03,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 51,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 2.54,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 144,
      delivery_time: 30.08,
      view_time: 11610.62,
      refinement_time: 6535.2,
      validation_time: 12.99,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 45,
      delivery_time: 0.0,
      view_time: 4532.22,
      refinement_time: 4534.54,
      validation_time: 2.32,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 4,
      delivery_time: 0.0,
      view_time: 0.15,
      refinement_time: 0.31,
      validation_time: 0.16,
    },
    {
      notification_send_date: '2024-03-19',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 5,
      delivery_time: 3141.02,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.28,
    },
    {
      notification_send_date: '2024-03-19',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 2,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.11,
    },
    {
      notification_send_date: '2024-03-19',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 27,
      delivery_time: 8518.04,
      view_time: 0.0,
      refinement_time: 13310.43,
      validation_time: 1.37,
    },
    {
      notification_send_date: '2024-03-19',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 7,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 3777.4,
      validation_time: 0.37,
    },
    {
      notification_send_date: '2024-03-19',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 7,
      delivery_time: 1.88,
      view_time: 0.0,
      refinement_time: 1177.93,
      validation_time: 0.33,
    },
    {
      notification_send_date: '2024-03-19',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 3,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.18,
    },
    {
      notification_send_date: '2024-03-19',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 8,
      delivery_time: 0.6,
      view_time: 186.83,
      refinement_time: 187.26,
      validation_time: 0.43,
    },
    {
      notification_send_date: '2024-03-19',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 3,
      delivery_time: 0.0,
      view_time: 793.39,
      refinement_time: 793.57,
      validation_time: 0.18,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 255,
      delivery_time: 148943.63,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 22.32,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 125,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 17.4,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 357,
      delivery_time: 133395.43,
      view_time: 0.0,
      refinement_time: 196116.4,
      validation_time: 23.46,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 118,
      delivery_time: 28.25,
      view_time: 0.0,
      refinement_time: 19863.48,
      validation_time: 10.2,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 71,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 40358.36,
      validation_time: 3.99,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 2,
      notifications_count: 2,
      delivery_time: 341.05,
      view_time: 0.0,
      refinement_time: 1061.12,
      validation_time: 0.07,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 4,
      notifications_count: 1,
      delivery_time: 170.8,
      view_time: 0.0,
      refinement_time: 530.88,
      validation_time: 0.08,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 2,
      notifications_count: 1,
      delivery_time: 168.18,
      view_time: 0.0,
      refinement_time: 336.24,
      validation_time: 0.07,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 103,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 5.44,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 151,
      delivery_time: 39.62,
      view_time: 13414.12,
      refinement_time: 8055.93,
      validation_time: 8.26,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 62,
      delivery_time: 0.0,
      view_time: 4967.3,
      refinement_time: 4970.54,
      validation_time: 3.24,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 3,
      delivery_time: 0.0,
      view_time: 0.09,
      refinement_time: 0.28,
      validation_time: 0.19,
    },
    {
      notification_send_date: '2024-03-22',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 3,
      delivery_time: 1336.66,
      view_time: 1401.67,
      refinement_time: 1401.84,
      validation_time: 0.18,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 250,
      delivery_time: 123743.68,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 13.45,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 126,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 7.1,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 273,
      delivery_time: 77689.7,
      view_time: 0.0,
      refinement_time: 127662.6,
      validation_time: 83.1,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 123,
      delivery_time: 28.08,
      view_time: 0.0,
      refinement_time: 20697.81,
      validation_time: 6.8,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 59,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 29064.7,
      validation_time: 3.01,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 2,
      notifications_count: 2,
      delivery_time: 338.16,
      view_time: 0.0,
      refinement_time: 1058.3,
      validation_time: 0.13,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 4,
      notifications_count: 2,
      delivery_time: 337.48,
      view_time: 0.0,
      refinement_time: 1057.59,
      validation_time: 0.11,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 109,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 6.38,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 113,
      delivery_time: 24.0,
      view_time: 7028.41,
      refinement_time: 4597.25,
      validation_time: 5.98,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 46,
      delivery_time: 0.0,
      view_time: 3023.76,
      refinement_time: 3043.1,
      validation_time: 19.34,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 3,
      delivery_time: 1471.52,
      view_time: 1542.06,
      refinement_time: 1542.21,
      validation_time: 0.15,
    },
    {
      notification_send_date: '2024-03-25',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 2,
      delivery_time: 0.0,
      view_time: 1.58,
      refinement_time: 1.69,
      validation_time: 0.11,
    },
    {
      notification_send_date: '2024-03-26',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 43,
      delivery_time: 19127.41,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 2.3,
    },
    {
      notification_send_date: '2024-03-26',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 46,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 35.6,
    },
    {
      notification_send_date: '2024-03-26',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 51,
      delivery_time: 16328.33,
      view_time: 0.0,
      refinement_time: 24728.69,
      validation_time: 19.51,
    },
    {
      notification_send_date: '2024-03-26',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 11,
      delivery_time: 4.85,
      view_time: 0.0,
      refinement_time: 1853.91,
      validation_time: 0.64,
    },
    {
      notification_send_date: '2024-03-26',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 31,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 1.71,
    },
    {
      notification_send_date: '2024-03-26',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 33,
      delivery_time: 7.19,
      view_time: 2204.79,
      refinement_time: 1380.9,
      validation_time: 1.76,
    },
    {
      notification_send_date: '2024-03-26',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 6,
      delivery_time: 0.0,
      view_time: 980.77,
      refinement_time: 981.13,
      validation_time: 0.37,
    },
    {
      notification_send_date: '2024-03-27',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 42,
      delivery_time: 17309.76,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 2.64,
    },
    {
      notification_send_date: '2024-03-27',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 2,
      notifications_count: 1,
      delivery_time: 169.2,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.08,
    },
    {
      notification_send_date: '2024-03-27',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 36,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 2.21,
    },
    {
      notification_send_date: '2024-03-27',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 22,
      delivery_time: 6811.49,
      view_time: 0.0,
      refinement_time: 10183.94,
      validation_time: 1.26,
    },
    {
      notification_send_date: '2024-03-27',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 13,
      delivery_time: 8.86,
      view_time: 0.0,
      refinement_time: 2193.55,
      validation_time: 0.75,
    },
    {
      notification_send_date: '2024-03-27',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 24,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 1.35,
    },
    {
      notification_send_date: '2024-03-27',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 13,
      delivery_time: 3.8,
      view_time: 1148.97,
      refinement_time: 884.65,
      validation_time: 0.73,
    },
    {
      notification_send_date: '2024-03-27',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 6,
      delivery_time: 0.0,
      view_time: 366.74,
      refinement_time: 367.14,
      validation_time: 0.4,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 201,
      delivery_time: 73192.47,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 44.78,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 3,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.17,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 2,
      notifications_count: 2,
      delivery_time: 339.26,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.08,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 231,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 31.3,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 62,
      delivery_time: 15.29,
      view_time: 0.0,
      refinement_time: 10433.42,
      validation_time: 3.41,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 6,
      delivery_time: 1567.65,
      view_time: 0.0,
      refinement_time: 2696.13,
      validation_time: 0.37,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 93,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 23.49,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 70,
      delivery_time: 14.75,
      view_time: 4921.6,
      refinement_time: 3614.68,
      validation_time: 3.86,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 33,
      delivery_time: 0.0,
      view_time: 3032.86,
      refinement_time: 3034.75,
      validation_time: 1.89,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 4,
      delivery_time: 0.0,
      view_time: 0.1,
      refinement_time: 0.31,
      validation_time: 0.21,
    },
    {
      notification_send_date: '2024-03-28',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 1,
      delivery_time: 353.96,
      view_time: 364.37,
      refinement_time: 364.43,
      validation_time: 0.06,
    },
    {
      notification_send_date: '2024-03-29',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 16,
      delivery_time: 6004.51,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.77,
    },
    {
      notification_send_date: '2024-03-29',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 11,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.5,
    },
    {
      notification_send_date: '2024-03-29',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 4,
      delivery_time: 2.25,
      view_time: 0.0,
      refinement_time: 674.81,
      validation_time: 0.2,
    },
    {
      notification_send_date: '2024-03-29',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 1,
      delivery_time: 239.71,
      view_time: 0.0,
      refinement_time: 427.6,
      validation_time: 0.04,
    },
    {
      notification_send_date: '2024-03-29',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 5,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.22,
    },
    {
      notification_send_date: '2024-03-29',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 3,
      delivery_time: 1.58,
      view_time: 179.22,
      refinement_time: 179.37,
      validation_time: 0.15,
    },
    {
      notification_send_date: '2024-04-02',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 188,
      delivery_time: 60189.26,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 9.6,
    },
    {
      notification_send_date: '2024-04-02',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 13,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.62,
    },
    {
      notification_send_date: '2024-04-02',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 338,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 62.27,
    },
    {
      notification_send_date: '2024-04-02',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 66,
      delivery_time: 17.14,
      view_time: 0.0,
      refinement_time: 11107.84,
      validation_time: 3.37,
    },
    {
      notification_send_date: '2024-04-02',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 75,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 3.51,
    },
    {
      notification_send_date: '2024-04-02',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 97,
      delivery_time: 16.54,
      view_time: 4996.98,
      refinement_time: 4189.05,
      validation_time: 5.0,
    },
    {
      notification_send_date: '2024-04-02',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 38,
      delivery_time: 0.0,
      view_time: 2532.39,
      refinement_time: 2534.41,
      validation_time: 2.02,
    },
    {
      notification_send_date: '2024-04-02',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 2,
      notifications_count: 1,
      delivery_time: 0.0,
      view_time: 104.33,
      refinement_time: 104.39,
      validation_time: 0.07,
    },
    {
      notification_send_date: '2024-04-02',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 1,
      delivery_time: 237.46,
      view_time: 246.53,
      refinement_time: 246.6,
      validation_time: 0.07,
    },
    {
      notification_send_date: '2024-04-03',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 16,
      delivery_time: 5166.57,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 1.0,
    },
    {
      notification_send_date: '2024-04-03',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 2,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.09,
    },
    {
      notification_send_date: '2024-04-03',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 38,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 2.44,
    },
    {
      notification_send_date: '2024-04-03',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 17,
      delivery_time: 9.16,
      view_time: 0.0,
      refinement_time: 2871.13,
      validation_time: 1.13,
    },
    {
      notification_send_date: '2024-04-03',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 6,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.32,
    },
    {
      notification_send_date: '2024-04-03',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 20,
      delivery_time: 9.26,
      view_time: 775.54,
      refinement_time: 753.5,
      validation_time: 1.21,
    },
    {
      notification_send_date: '2024-04-03',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 2,
      delivery_time: 0.0,
      view_time: 84.11,
      refinement_time: 84.22,
      validation_time: 0.11,
    },
    {
      notification_send_date: '2024-04-04',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 4,
      delivery_time: 1188.26,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.26,
    },
    {
      notification_send_date: '2024-04-04',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 15,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.99,
    },
    {
      notification_send_date: '2024-04-04',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 2,
      delivery_time: 0.16,
      view_time: 0.0,
      refinement_time: 336.15,
      validation_time: 0.08,
    },
    {
      notification_send_date: '2024-04-04',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 1,
      delivery_time: 0.11,
      view_time: 24.23,
      refinement_time: 24.29,
      validation_time: 0.06,
    },
    {
      notification_send_date: '2024-04-05',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 2,
      notifications_count: 1,
      delivery_time: 170.18,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.07,
    },
    {
      notification_send_date: '2024-04-05',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 267,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 21.25,
    },
    {
      notification_send_date: '2024-04-05',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 25,
      delivery_time: 7.47,
      view_time: 0.0,
      refinement_time: 4209.36,
      validation_time: 1.29,
    },
    {
      notification_send_date: '2024-04-05',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 19,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.88,
    },
    {
      notification_send_date: '2024-04-05',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 36,
      delivery_time: 5.26,
      view_time: 2163.41,
      refinement_time: 1897.35,
      validation_time: 1.86,
    },
    {
      notification_send_date: '2024-04-05',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 21,
      delivery_time: 0.0,
      view_time: 1016.93,
      refinement_time: 1017.99,
      validation_time: 1.06,
    },
    {
      notification_send_date: '2024-04-05',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 1,
      notifications_count: 1,
      delivery_time: 1.2,
      view_time: 94.24,
      refinement_time: 94.29,
      validation_time: 0.05,
    },
    {
      notification_send_date: '2024-04-08',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 1,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.05,
    },
    {
      notification_send_date: '2024-04-08',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 2,
      notifications_count: 1,
      delivery_time: 170.63,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.04,
    },
    {
      notification_send_date: '2024-04-08',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 4,
      notifications_count: 1,
      delivery_time: 169.33,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.05,
    },
    {
      notification_send_date: '2024-04-08',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 2,
      notifications_count: 1,
      delivery_time: 168.13,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.04,
    },
    {
      notification_send_date: '2024-04-08',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 333,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 18.55,
    },
    {
      notification_send_date: '2024-04-08',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 41,
      delivery_time: 2.61,
      view_time: 0.0,
      refinement_time: 6892.41,
      validation_time: 2.31,
    },
    {
      notification_send_date: '2024-04-08',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.UNREACHABLE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 30,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 1.73,
    },
    {
      notification_send_date: '2024-04-08',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 31,
      delivery_time: 3.14,
      view_time: 966.95,
      refinement_time: 957.78,
      validation_time: 1.79,
    },
    {
      notification_send_date: '2024-04-08',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 20,
      delivery_time: 0.0,
      view_time: 423.95,
      refinement_time: 425.08,
      validation_time: 1.12,
    },
    {
      notification_send_date: '2024-04-10',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.KO,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 2,
      notifications_count: 1,
      delivery_time: 173.27,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.07,
    },
    {
      notification_send_date: '2024-04-10',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 364,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 270.03,
    },
    {
      notification_send_date: '2024-04-10',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 43,
      delivery_time: 57.36,
      view_time: 0.0,
      refinement_time: 7349.22,
      validation_time: 68.28,
    },
    {
      notification_send_date: '2024-04-10',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 49,
      delivery_time: 34.04,
      view_time: 971.54,
      refinement_time: 1001.76,
      validation_time: 30.22,
    },
    {
      notification_send_date: '2024-04-10',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 14,
      delivery_time: 0.0,
      view_time: 55.97,
      refinement_time: 85.11,
      validation_time: 29.14,
    },
    {
      notification_send_date: '2024-04-12',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 142,
      delivery_time: 50.42,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 37.91,
    },
    {
      notification_send_date: '2024-04-12',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 958,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 331.06,
    },
    {
      notification_send_date: '2024-04-12',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 122,
      delivery_time: 39.51,
      view_time: 4767.68,
      refinement_time: 4812.51,
      validation_time: 44.83,
    },
    {
      notification_send_date: '2024-04-12',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 50,
      delivery_time: 0.0,
      view_time: 585.1,
      refinement_time: 605.5,
      validation_time: 20.4,
    },
    {
      notification_send_date: '2024-04-12',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 7,
      delivery_time: 0.0,
      view_time: 1.11,
      refinement_time: 3.66,
      validation_time: 2.55,
    },
    {
      notification_send_date: '2024-04-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.ACCEPTED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 413,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 36.92,
    },
    {
      notification_send_date: '2024-04-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 264,
      delivery_time: 110.23,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 23.3,
    },
    {
      notification_send_date: '2024-04-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 1,
      notifications_count: 2,
      delivery_time: 3.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.09,
    },
    {
      notification_send_date: '2024-04-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 1047,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 69.09,
    },
    {
      notification_send_date: '2024-04-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.PROGRESS,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 1,
      notifications_count: 4,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.26,
    },
    {
      notification_send_date: '2024-04-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.PROGRESS,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 2,
      notifications_count: 3,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.12,
    },
    {
      notification_send_date: '2024-04-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 224,
      delivery_time: 66.23,
      view_time: 2668.92,
      refinement_time: 2701.6,
      validation_time: 32.68,
    },
    {
      notification_send_date: '2024-04-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 68,
      delivery_time: 0.0,
      view_time: 285.09,
      refinement_time: 294.59,
      validation_time: 9.5,
    },
    {
      notification_send_date: '2024-04-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 2,
      delivery_time: 0.0,
      view_time: 0.62,
      refinement_time: 0.75,
      validation_time: 0.12,
    },
    {
      notification_send_date: '2024-04-16',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.ACCEPTED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 81,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 4.55,
    },
    {
      notification_send_date: '2024-04-16',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 48,
      delivery_time: 18.01,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 2.78,
    },
    {
      notification_send_date: '2024-04-16',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 240,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 16.7,
    },
    {
      notification_send_date: '2024-04-16',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 33,
      delivery_time: 8.18,
      view_time: 301.05,
      refinement_time: 303.07,
      validation_time: 2.02,
    },
    {
      notification_send_date: '2024-04-16',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 14,
      delivery_time: 0.0,
      view_time: 101.28,
      refinement_time: 102.05,
      validation_time: 0.77,
    },
    {
      notification_send_date: '2024-04-17',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.ACCEPTED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 187,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 21.27,
    },
    {
      notification_send_date: '2024-04-17',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 129,
      delivery_time: 64.7,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 14.37,
    },
    {
      notification_send_date: '2024-04-17',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 509,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 75.89,
    },
    {
      notification_send_date: '2024-04-17',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.PROGRESS,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 2,
      notifications_count: 2,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.09,
    },
    {
      notification_send_date: '2024-04-17',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.PROGRESS,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 1,
      notifications_count: 1,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.2,
    },
    {
      notification_send_date: '2024-04-17',
      notification_request_status: NotificationStatus.REFUSED,
      notification_status: NotificationStatus.REFUSED,
      notification_type: DeliveryMode.UNKNOWN,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 2,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 31.28,
    },
    {
      notification_send_date: '2024-04-17',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 55,
      delivery_time: 23.9,
      view_time: 143.47,
      refinement_time: 147.79,
      validation_time: 4.32,
    },
    {
      notification_send_date: '2024-04-17',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 31,
      delivery_time: 0.0,
      view_time: 32.31,
      refinement_time: 35.34,
      validation_time: 3.03,
    },
    {
      notification_send_date: '2024-04-17',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.VIEWED,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'NO',
      notification_viewed: 'SI',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 5,
      delivery_time: 0.0,
      view_time: 0.37,
      refinement_time: 0.77,
      validation_time: 0.4,
    },
  ],
  digital_notification_focus: [
    {
      notification_send_date: '2024-03-15',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 11,
      notifications_count: 4,
    },
    {
      notification_send_date: '2024-03-15',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 234,
    },
    {
      notification_send_date: '2024-03-18',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 7,
      notifications_count: 4,
    },
    {
      notification_send_date: '2024-03-18',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 227,
    },
    {
      notification_send_date: '2024-03-19',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 15,
    },
    {
      notification_send_date: '2024-03-22',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 10,
      notifications_count: 4,
    },
    {
      notification_send_date: '2024-03-22',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 272,
    },
    {
      notification_send_date: '2024-03-25',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 12,
      notifications_count: 4,
    },
    {
      notification_send_date: '2024-03-25',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 238,
    },
    {
      notification_send_date: '2024-03-26',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 44,
    },
    {
      notification_send_date: '2024-03-27',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 2,
      notifications_count: 1,
    },
    {
      notification_send_date: '2024-03-27',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 26,
    },
    {
      notification_send_date: '2024-03-28',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 4,
      notifications_count: 2,
    },
    {
      notification_send_date: '2024-03-28',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 136,
    },
    {
      notification_send_date: '2024-03-29',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 7,
    },
    {
      notification_send_date: '2024-04-02',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 2,
      notifications_count: 1,
    },
    {
      notification_send_date: '2024-04-02',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 163,
    },
    {
      notification_send_date: '2024-04-03',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 37,
    },
    {
      notification_send_date: '2024-04-04',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 3,
    },
    {
      notification_send_date: '2024-04-05',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 3,
      notifications_count: 2,
    },
    {
      notification_send_date: '2024-04-05',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 61,
    },
    {
      notification_send_date: '2024-04-08',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 8,
      notifications_count: 3,
    },
    {
      notification_send_date: '2024-04-08',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 72,
    },
    {
      notification_send_date: '2024-04-10',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 2,
      notifications_count: 1,
    },
    {
      notification_send_date: '2024-04-10',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 92,
    },
    {
      notification_send_date: '2024-04-12',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 271,
    },
    {
      notification_send_date: '2024-04-15',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 11,
      notifications_count: 8,
    },
    {
      notification_send_date: '2024-04-15',
      error_type: DigitaErrorTypes.INVALID_PEC,
      failed_attempts_count: 1,
      notifications_count: 1,
    },
    {
      notification_send_date: '2024-04-15',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 490,
    },
    {
      notification_send_date: '2024-04-16',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 81,
    },
    {
      notification_send_date: '2024-04-17',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 5,
      notifications_count: 3,
    },
    {
      notification_send_date: '2024-04-17',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 189,
    },
  ],
};
