export enum PAEventsType {
  /* API KEYS */
  SEND_PA_ADD_API_START = 'SEND_PA_ADD_API_START',
  SEND_PA_ADD_API_UX_SUCCESS = 'SEND_PA_ADD_API_UX_SUCCESS',
  SEND_PA_API_INTEGRATIONS = 'SEND_PA_API_INTEGRATIONS',

  /* ERROR */
  SEND_PA_TOAST_ERROR = 'SEND_PA_TOAST_ERROR',

  /* NEW NOTIFICATION */
  SEND_PA_DEBT_POSITION = 'SEND_PA_DEBT_POSITION',
  SEND_PA_DEBT_POSITION_DETAIL = 'SEND_PA_DEBT_POSITION_DETAIL',
  SEND_PA_DOCUMENTATION = 'SEND_PA_DOCUMENTATION',
  SEND_PA_NEW_NOTIFICATION = 'SEND_PA_NEW_NOTIFICATION',
  SEND_PA_NEW_NOTIFICATION_UX_SUCCESS = 'SEND_PA_NEW_NOTIFICATION_UX_SUCCESS',
  SEND_PA_PRELIMINARY_INFORMATION = 'SEND_PA_PRELIMINARY_INFORMATION',
  SEND_PA_RECIPIENTS = 'SEND_PA_RECIPIENTS',

  /* NOTIFICATION */
  SEND_PA_CANCEL_NOTIFICATION = 'SEND_PA_CANCEL_NOTIFICATION',
  SEND_PA_NOTIFICATION_DETAIL = 'SEND_PA_NOTIFICATION_DETAIL',
  SEND_PA_NOTIFICATION_DOWNLOAD_ATTACHMENT = 'SEND_PA_NOTIFICATION_DOWNLOAD_ATTACHMENT',
  SEND_PA_NOTIFICATIONS = 'SEND_PA_NOTIFICATIONS',
  SEND_PA_TIMELINE_DOWNLOAD = 'SEND_PA_TIMELINE_DOWNLOAD',
  SEND_PA_TIMELINE_SHOW_HISTORY = 'SEND_PA_TIMELINE_SHOW_HISTORY',
  SEND_PA_TIMELINE_SHOW_MORE = 'SEND_PA_TIMELINE_SHOW_MORE',

  /* SERVICE STATUS */
  SEND_PA_SERVICE_STATUS = 'SEND_PA_SERVICE_STATUS',

  /* STATISTICS */
  SEND_PA_STATISTICS = 'SEND_PA_STATISTICS',

  /* SUPER PROPERTIES */
  SEND_PA_HAS_NOTIFICATIONS = 'SEND_PA_HAS_NOTIFICATIONS',
}
