import {
  DeliveryMode,
  DigitaErrorTypes,
  NotificationStatus,
  ResponseStatus,
  StatisticsDataTypes,
  StatisticsParsedData,
  StatisticsResponse,
} from '../models/Statistics';

export const rawDataMock: StatisticsResponse = {
  sender_id: 'sender-id',
  genTimestamp: '2024-04-24T11:09:36.432251Z',
  lastDate: '2024-04-21',
  startDate: '2023-12-06',
  endDate: '2024-04-24',
  notificationsOverview: [
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 49,
      delivery_time: 35419.6,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 2.77,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 4,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 0.11,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 38,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 67.24,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 564,
      delivery_time: 257041.82,
      view_time: 0.0,
      refinement_time: 345965.16,
      validation_time: 31.62,
    },
    {
      notification_send_date: '2024-03-15',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 133,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 83487.85,
      validation_time: 7.63,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERED,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 54,
      delivery_time: 37194.88,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 8.47,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.DELIVERING,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'NO',
      attempt_count_per_digital_notification: 0,
      notifications_count: 41,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 0.0,
      validation_time: 1.95,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 574,
      delivery_time: 216403.54,
      view_time: 0.0,
      refinement_time: 311443.92,
      validation_time: 40.56,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.ANALOG,
      status_digital_delivery: ResponseStatus.UNKNOWN,
      notification_delivered: 'NO',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 134,
      delivery_time: 0.0,
      view_time: 0.0,
      refinement_time: 74775.4,
      validation_time: 7.1,
    },
    {
      notification_send_date: '2024-03-18',
      notification_request_status: NotificationStatus.ACCEPTED,
      notification_status: NotificationStatus.EFFECTIVE_DATE,
      notification_type: DeliveryMode.DIGITAL,
      status_digital_delivery: ResponseStatus.OK,
      notification_delivered: 'SI',
      notification_viewed: 'NO',
      notification_refined: 'SI',
      attempt_count_per_digital_notification: 0,
      notifications_count: 79,
      delivery_time: 16.77,
      view_time: 0.0,
      refinement_time: 13292.18,
      validation_time: 4.13,
    },
  ],
  digitalNotificationFocus: [
    {
      notification_send_date: '2024-03-15',
      error_type: DigitaErrorTypes.DELIVERY_ERROR,
      failed_attempts_count: 11,
      notifications_count: 4,
    },
    {
      notification_send_date: '2024-03-15',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 234,
    },
    {
      notification_send_date: '2024-03-18',
      error_type: DigitaErrorTypes.INVALID_PEC,
      failed_attempts_count: 7,
      notifications_count: 4,
    },
    {
      notification_send_date: '2024-03-18',
      error_type: DigitaErrorTypes.UNKNOWN,
      failed_attempts_count: 0,
      notifications_count: 227,
    },
  ],
};

export const parsedDataMock: StatisticsParsedData = {
  [StatisticsDataTypes.FiledStatistics]: {
    [NotificationStatus.ACCEPTED]: {
      count: 1670,
      details: [
        { send_date: '2024-03-15', count: 788 },
        { send_date: '2024-03-18', count: 882 },
      ],
    },
    [NotificationStatus.REFUSED]: { count: 0, details: [] },
  },
  [StatisticsDataTypes.LastStateStatistics]: {
    [NotificationStatus.ACCEPTED]: 0,
    [NotificationStatus.REFUSED]: 0,
    [NotificationStatus.DELIVERING]: 79,
    [NotificationStatus.DELIVERED]: 107,
    [NotificationStatus.VIEWED]: 0,
    [NotificationStatus.EFFECTIVE_DATE]: 1484,
    [NotificationStatus.CANCELLED]: 0,
    [NotificationStatus.UNREACHABLE]: 0,
  },
  [StatisticsDataTypes.DeliveryModeStatistics]: {
    [DeliveryMode.ANALOG]: {
      count: 1591,
      details: [
        { send_date: '2024-03-15', count: 788 },
        { send_date: '2024-03-18', count: 803 },
      ],
    },
    [DeliveryMode.DIGITAL]: {
      count: 79,
      details: [{ send_date: '2024-03-18', count: 79 }],
    },
    [DeliveryMode.UNKNOWN]: {
      count: 0,
      details: [],
    },
  },
  [StatisticsDataTypes.DigitalStateStatistics]: {
    [ResponseStatus.OK]: 79,
    [ResponseStatus.KO]: 0,
    [ResponseStatus.PROGRESS]: 0,
    [ResponseStatus.UNKNOWN]: 0,
  },
  [StatisticsDataTypes.DigitalMeanTimeStatistics]: {
    delivered: { count: 79, time: 16.77 },
    viewed: { count: 0, time: 0 },
    refined: { count: 79, time: 13292.18 },
  },
  [StatisticsDataTypes.DigitalErrorsDetailStatistics]: {
    [DigitaErrorTypes.INVALID_PEC]: { count: 4, attempts: 7 },
    [DigitaErrorTypes.DELIVERY_ERROR]: { count: 4, attempts: 11 },
    [DigitaErrorTypes.REJECTED]: { count: 0, attempts: 0 },
    [DigitaErrorTypes.UNKNOWN]: { count: 461, attempts: 0 },
  },
};
