export enum NotificationStatus {
  IN_VALIDATION = 'IN_VALIDATION',
  ACCEPTED = 'ACCEPTED',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  VIEWED = 'VIEWED',
  EFFECTIVE_DATE = 'EFFECTIVE_DATE',
  PAID = 'PAID',
  UNREACHABLE = 'UNREACHABLE',
  CANCELLED = 'CANCELLED',
  REFUSED = 'REFUSED',
  RETURNED_TO_SENDER = 'RETURNED_TO_SENDER',
  // only fe
  CANCELLATION_IN_PROGRESS = 'CANCELLATION_IN_PROGRESS',
}
