name: Release branch action
on:
  schedule:
    # Runs "At 16:00 on Friday every two weeks"
    # - cron: '16 * * 5 [ $(expr $(date +%W) % 2) -eq 1 ]'
    # Runs "Every 5 minutes (for testing)"
    - cron: "*/5 * * * *"
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  release_branch:
    runs-on: windows-latest
    steps:
      - name: Create release branch
        run: |
          ./script/create_release_branch.sh \
            -b $BASE_BRANCH \
            -v $VERSION
        env:
          BASE_BRANCH: develop
          VERSION: patch
