name: Update BFF Dependency

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "develop"
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Install Packages
        run: cd .github/workflows/actions/update-dependency && npm install

      - name: Update BFF Dependency
        uses: ./.github/workflows/actions/update-dependency
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: "develop"
